version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    networks:
      - app-network

  ml_model:
    build:
      context: ../model_backend
      dockerfile: Dockerfile
    ports:
        - "8085:80"
    environment:
      BEARER_TOKEN: your_secure_token
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - ml_model
    ports:
      - "8181:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: backend
      ML_MODEL_URL: http://ml_model/predict
      BEARER_TOKEN: your_secure_token
    networks:
      - app-network

networks:
  app-network:
