version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: serviceclassification
      POSTGRES_PASSWORD: serviceclassification
      POSTGRES_DB: backend
    networks:
      - app-network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U serviceclassification -d backend " ]
      interval: 10s
      timeout: 5s
      retries: 5

  ml_model:
    build:
      context: ../model_backend
      dockerfile: Dockerfile
    ports:
        - "8085:80"
    environment:
      BEARER_TOKEN: your_secure_token
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      kb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: serviceclassification
      DB_PASSWORD: serviceclassification
      DB_NAME: backend
      ML_MODEL_URL: http://ml_model/predict
      BEARER_TOKEN: your_secure_token
#      PUBLIC_HOST: 194.135.25.202
      PUBLIC_HOST: localhost
      KB_HOST: kb
      KB_PORT: 3030
      KB_DATASET: service-classification
      KB_LOGIN: admin
      KB_PASSWORD: serviceclassification
    networks:
      - app-network

  kb:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: serviceclassification
      FUSEKI_DATASET_1: service-classification
      JVM_ARGS: -Xmx512M
      TDB: 2
    volumes:
      - kb-data:/fuseki
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3030/$$/ping" ]
    depends_on:
      kb-migration:
        condition: service_completed_successfully

  kb-migration:
    image: stain/jena-fuseki
    environment:
      ADMIN_PASSWORD: serviceclassification
      FUSEKI_DATASET_1: service-classification
      JVM_ARGS: -Xmx512M
      TDB: 2
    volumes:
      - type: bind
        source: ./rdf_migrations
        target: /staging
      - kb-data:/fuseki
    entrypoint: ["/jena-fuseki/tdbloader2", "--loc", "/fuseki/databases/service-classification",  "/staging/service-classification.ttl"]
    restart: "no"

volumes:
  kb-data:

networks:
  app-network:
